package console.constant;

public interface CommandArgumentsConstants {
    int INIT_ARGUMENTS_COUNT_GROUND = 1;
    int SAVE_ARGUMENTS_COUNT_GROUND = 2;
    int READ_ARGUMENTS_COUNT_GROUND = 2;
    int PRINT_TREE_ARGUMENTS_COUNT_GROUND = 1;
    int PRINT_INDENT_ARGUMENTS_COUNT_GROUND = 1;
    int REDO_ARGUMENTS_COUNT_GROUND = 1;
    int UNDO_ARGUMENTS_COUNT_GROUND = 1;
    int INSERT_ARGUMENTS_COUNT_GROUND = 4;
    int APPEND_ARGUMENTS_COUNT_GROUND = 4;
    int EDIT_ID_ARGUMENTS_COUNT_GROUND = 3;
    int EDIT_TEXT_ARGUMENTS_COUNT_GROUND = 2;
    int DELETE_ARGUMENTS_COUNT_GROUND = 2;
    int SPELL_CHECK_ARGUMENTS_COUNT_GROUND = 1;
}
